### ISSUE TITLE
Adding insee/postal codes

### ISSUE THREAD

**Issue by davidbgk** [cquest/fusion-communes-2016#2]
Is there a way to retrieve the associated insee/postal code for new municipalities?

I need both to merge data from https://github.com/etalab/geozones

**Comment by davidbgk** [comment]
Thanks for the addition, what happens when the `insee_nouvelle` column is empty?

**Comment by parville** [comment]
Le connaissant, si @cquest ne met pas la valeur c'est qu'il ne l'a pas ! 
Pour ma part je me mets en chasse pour 27, 76, 14, 50 et 61

**Comment by cquest** [comment]
Si insee_nouvelle manque c'est parce que je n'ai pas d'info sur le chef-lieu de la commune nouvelle.
A rechercher dans les arrêtés, pour compléter fusion.csv...

**Comment by cquest** [comment]
En progrès pour 2017... ;)
https://github.com/cquest/fusion-communes/blob/master/2017/fusion2017.json
