### ISSUE TITLE
Error Fusion 2016 details

### ISSUE THREAD

**Issue by CorentinJacob** [cquest/fusion-communes-2016#3]
J'ai remarqué 2 erreurs avec ma table communes de l'INSEE au niveau de ces 2 nouvelles communes à propos du fichier 
"Fichier détail avec codes INSEE en 2016" .

![image](https://cloud.githubusercontent.com/assets/10074049/22504466/cb8956e4-e876-11e6-8a30-7a7ba4530884.png)

![image](https://cloud.githubusercontent.com/assets/10074049/22504487/e885ec80-e876-11e6-8fc2-ca2b7be16999.png)

Code INSEE de la "La Vespière-Friardel" : 14740 
Dans le fichier :
"14","La Vespière-Friardel","14292","Friardel","14292"
"14","La Vespière-Friardel","14292","La Vespière","14740"
Dans le fichier : 
Code INSEE de la "Mazé-Milon" : 49194
"49","Mazé-Milon","49139","Fontaine-Milon","49139"
"49","Mazé-Milon","49139","Mazé","49194"

Ce n'est pas indiqué dans votre fichier, il y a eu également ce changement qui n'est pas indiqué:
https://fr.wikipedia.org/wiki/L%27Oudon ->
"Un nouvel arrêté préfectoral, le 7 janvier 2014, fait de la commune de Notre-Dame-de-Fresnay le nouveau chef-lieu. Afin de prendre en compte ce transfert de chef lieu, lors de la publication du COG 2016 l'INSEE décide de modifier le code commune de L'Oudon pour reprendre l'ancien code de Notre-Dame-de-Fresnay (14472)." 

2015 : 
![image](https://cloud.githubusercontent.com/assets/10074049/22505194/6b04bc9c-e87a-11e6-90ed-330d80f8a888.png)

2016:
![image](https://cloud.githubusercontent.com/assets/10074049/22505203/766ee1f2-e87a-11e6-8f16-b145d14207f8.png)

**Comment by parville** [comment]
Attention en 2017, L'Oudon a fusionné à son tour dans une autre ...

**Comment by CorentinJacob** [comment]
Dans ce cas là, cela intervient dans la fusion de 2017. personnellement je me sers de ces données pour faire rendre une table de statistiques de 2015 compatible avec ma table des communes de 2016 de l'INSEE.
